#!/bin/bash
# Ustawienie szerokości kolumny dla nazw plików
width=20  

for file in *.json; do
    # Pobranie salda dla danego pliku
    balance=$(~/tachyon/target/release/solana balance --keypair "$file")
    
    # Formatowanie i wyświetlanie wyniku
    printf "%-${width}s %s\n" "$file:" "[SOL] $balance"
done
